### ISSUE TITLE
"Convert" does nothing with UI Editor tool in use

### ISSUE THREAD

**Issue by alertcoderf** [Quenty/ClassConverterPlugin#2]
Clicking "convert" won't do anything, and will deselect everything if UI Editor is being used

**Comment by Citrecs** [comment]
I would like to second this, the recent update with the UI editor has broken this plugin. I believe this could be fixed by switching the plugin from being a CoreGui to the new Plugin Gui system, which I would totally love because designing UI without this plugin is extraordinarily annoying

**Comment by alertcoderf** [comment]
> I would like to second this, the recent update with the UI editor has broken this plugin. I believe this could be fixed by switching the plugin from being a CoreGui to the new Plugin Gui system, which I would totally love because designing UI without this plugin is extraordinarily annoying

For now, you can turn off StarterGui>ShowDevelopmentGui and the plugin will work just fine. An irritating hindrance, but it's the only workaround I've found thus far with the new UI editor.

**Comment by Quenty** [comment]
I'll look into this. The solution is to move this plugin into its own Gui window.
