### ISSUE TITLE
Plugin button not registering

### ISSUE THREAD

**Issue by vocksel** [Quenty/ClassConverterPlugin#3]
After updating, the plugin button is no longer appearing in the Plugins bar.

This bit of code should be registering the plugin button under the "Object" toolbar, yet it doesn't appear.
https://github.com/Quenty/ClassConverterPlugin/blob/master/src/init.server.lua#L163-L169

I have the part to terrain plugin installed which uses the same toolbar, and its button is registered like normal.

The only output is "Loaded class converter" with no errors.

**Comment by Quenty** [comment]
Can't believe I missed this. There's a conditional return in my code! 

https://github.com/Quenty/ClassConverterPlugin/blob/158300775776dd535fbe8dfa5936cd5b1fe2f65b/src/init.server.lua#L150

Will be fixed soon!
